# Generated by Django 4.1.1 on 2022-10-04 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_member_id_roommember_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoomName', models.CharField(max_length=200)),
                ('Available', models.BooleanField(default=True)),
                ('max', models.IntegerField()),
            ],
        ),
    ]
